---

- name: Install OpenStack Packages (OpenStack Client) in Ubuntu
  shell: |
    sudo dpkg --configure -a
    sudo apt install python3-openstackclient -y
  when: ansible_distribution == "Ubuntu"

- name: Install OpenStack Packages in CentOS
  shell: |
    sudo yum install python3-openstackclient -y
  when: ansible_distribution == "CentOS"

- name: Install OpenStack Packages (Nova)
  package:
    name: nova-compute
    state: latest
