---

- hosts: all
  become: true
  tasks:

#  - name: Update Repository Index and Adding Universe Repository
#    shell: |
#     sudo apt update | sudo apt upgrade -y
     # sudo add-apt-repository universe
#    when: ansible_distribution == "Ubuntu"

- hosts: compute
  become: true
  roles:
#    - os_packages

- hosts: controller
  become: true
  roles:
#    - ntp
#    - sql_database
#    - message_q
    - memcached
#    - etcd

