---

- name: Install SQL Database in Ubuntu
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Creating file for SQL Database in Ubuntu
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch
  when: ansible_distribution == "Ubuntu"

- name: Editing created file for SQL Database in Ubuntu
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: present
    line: "{{ item }}"
  with_items:
  - [mysqld]
  - bind-address = 10.0.0.11
  - default-storage-engine = innodb
  - innodb_file_per_table = on
  - max_connections = 4096
  - collation-server = utf8_general_ci
  - character-set-server = utf8
  when: ansible_distribution == "Ubuntu"

- name: Restarting SQL Database in Ubuntu
  service:
    name: mysql
    state: restarted
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Install SQL Database in CentOS
  yum:
    name:
      - mariadb
      - mariadb-server
    state: latest
  when: ansible_distribution == "CentOS"

- name: Creating file for SQL Database in CentOS
  file:
    path: /etc/my.cnf.d/openstack.cnf
    state: touch
  when: ansible_distribution == "CentOS"

- name: Editing created file for SQL Database in CentOS
  ansible.builtin.lineinfile:
    path: /etc/my.cnf.d/openstack.cnf
    state: present
    line: "{{ item }}"
  with_items:
  - [mysqld]
  - bind-address = 10.0.0.11
  - default-storage-engine = innodb
  - innodb_file_per_table = on
  - max_connections = 4096
  - collation-server = utf8_general_ci
  - character-set-server = utf8
  when: ansible_distribution == "CentOS"

- name: Enabling and starting SQL Database in CentOS
  service:
    name: mariadb
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
