---

- name: Download Etcd Release
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v3.4.28/etcd-v3.4.28-linux-amd64.tar.gz"
    dest: "/tmp/etcd-v3.4.28-linux-amd64.tar.gz"

- name: Extracting downloaded file
  unarchive:
    src: "/tmp/etcd-v3.4.28-linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Move the file
  shell:
    mv /tmp/etcd-v3.4.28-linux-amd64/etcd /usr/local/bin

- name: Creating etcd.service file in Ubuntu
  copy:
    content: |
      [Unit]
      Description=etcd - highly-available key value store
      Documentation=https://etcd.io/docs/
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/etcd
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/etcd.service

- name: Reloading
  shell: sudo systemctl daemon-reload

- name: Enabling Etcd
  service:
    name: etcd
    state: started
    enabled: yes

