---

- name: Install Memcached
  package:
    name: memcached
    state: latest

- name: Editing memcached.conf in Ubuntu
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/memcached.conf
    regexp: "-l 127.0.0.1"
    line: "-l 10.0.0.11"
    backup: yes
  when: ansible_distribution == "Ubuntu"

- name: Editing memcached in CentOS
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/sysconfig/memcached
    regexp: 'OPTIONS = "-l 127.0.0.1,::1"'
    line: 'OPTIONS = "-l 127.0.0.1,::1,controller"'
  when: ansible_distribution == "CentOS"

- name: Enabling Memcached
  shell: |
    sudo systemctl enable memcached
    sudo systemctl start memcached
